### ISSUE TITLE
Exercice absent fichier exercices/02.js 

### ISSUE THREAD

**Issue by AlexSnooTwo** [MikeCodeur/react-patterns#2]
Le fichier n'est pas le bon, c'est un fichier qui contient déjà la solution et non pas un fichier d'exercice

**Comment by nadlgit** [comment]
Idem

**Comment by MikeCodeur** [comment]
Merci de m'avoir remonté cela : fix https://github.com/MikeCodeur/react-patterns/commit/5657782fa1b843ae3bed6e41da114f2ad7ae7b9b
